### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by jmuzsik** [dominictarr/usbtether#1]
How was this done? What's the trick? 1969 that is

**Comment by jmuzsik** [comment]
Figured it out, idk if both commiter and author date are necessary:

`GIT_COMMITTER_DATE="Thu, 01 Jan 1970 00:00:00 GMT" GIT_AUTHOR_DATE="Thu, 01 Jan 1970 00:00:00 GMT" git commit --date="Thu, 01 Jan 1970 00:00:00 GMT" -m "This may work"`

Thanks for the inspiration!

**Comment by dominictarr** [comment]
I wrote this on a raspberry pi, turned out the date was set wrong. but the timezone was right, to NZ, +12 hours ahead, hadn't gotten to utc 0 yet.
